coverage:
  precision: 2
  range: "70...100"
  round: down

  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 1%
    patch:
      default:
        enabled: yes
        only_pulls: true
        target: auto
        threshold: 1%
    changes: no
  ignore:
    - "vendor/*"

comment:
  layout: "header, diff, tree, changes, sunburst"
