coverage:
  precision: 2
  range: "70...100"
  round: down

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        only_pulls: true
        target: 50%
        threshold: 5%
    changes: false
  ignore:
    - "vendor/*"

comment:
  layout: "header, diff, tree, changes, sunburst"
