runner:

  golint:
    cmd: "golint ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  govet:
    cmd: "go vet ./pkg/..."

  misspell:
    cmd: "misspell ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  unused:
    cmd: "unused ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  gosimple:
    cmd: "gosimple ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  varcheck:
    cmd: "varcheck ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  structcheck:
    cmd: "structcheck ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  staticcheck:
    cmd: "staticcheck -ignore '*_test.go' ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  errcheck:
    cmd: "errcheck -ignore 'io:.*,ioutil:.*,net/http:.*' -asserts -ignoretests ./pkg/..."
    errorformat:
      - "%f:%l:%c:%m"

  unconvert:
    cmd: "unconvert ./pkg/..."
    errorformat:
      - "%f:%l:%c: %m"

  ineffassign:
    cmd: "gometalinter --vendor --disable-all --enable=ineffassign ./pkg/..."
    errorformat:
      - "%f:%l:%c:%s: %m"

  deadcode:
    cmd: "gometalinter --vendor --disable-all --enable=deadcode ./pkg/..."
    errorformat:
      - "%f:%l:%c:%s: %m"

  gas:
    cmd: "gometalinter --vendor --disable-all --enable=gas --exclude='Errors unhandled' ./pkg/..."
    errorformat:
      - "%f:%l::%s: %m,%s,%s"
