sudo: required
dist: trusty

services: docker
language: go
go:
  - 1.7.3

before_install:
  - go get github.com/mattn/goveralls

install:
  - docker build --rm -t zchee/nvim-go .

script:
  - docker run --rm -v $PWD:/nvim-go zchee/nvim-go

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
