sudo: required
dist: trusty

services: docker
language: generic

env:
  - COVERAGE=codecov

install:
  - docker build -t zchee/nvim-go .

script:
  - docker run -e COVERAGE_SERVICE=$COVERAGE -v $PWD:/nvim-go zchee/nvim-go

after_success:
  - bash <(curl -s https://codecov.io/bash)
