image: golang:1.7beta1

pipelines:
  default:
    - step:
        script:
          - env
          - curl -sSL "https://github.com/neovim/neovim/releases/download/nightly/neovim-linux64.tar.gz" -o /tmp/neovim-linux64.tar.gz
          - mkdir -p /tmp/neovim /usr/local/bin /usr/local/share 
          - tar -xzf /tmp/neovim-linux64.tar.gz -C /tmp
          - mv /tmp/neovim-linux64/bin/nvim /usr/local/bin
          - mv /tmp/neovim-linux64/share/nvim /usr/local/share
          - go get -u -v -x github.com/constabulary/gb/...
          - gb test -v -race -bench=. -benchmem
