image: golang:1.7beta1

pipelines:
  default:
    - step:
        script:
          - env
          - wget -q -O - https://github.com/neovim/neovim/releases/download/nightly/neovim-linux64.tar.gz | tar xzf - --strip-components=1 -C "/usr/local"
          - nvim --version
          - go get -u -v -x github.com/constabulary/gb/...
          - gb test -v -race -bench=. -benchmem
