version: 2
executorType: docker

containerInfo:
  - image: golang:1.8

stages:
  build:
    workDir: /go/src/github.com/zchee/nvim-go
    environment:
      CIRCLE_PROJECT_USERNAME: zchee
      CIRCLE_PROJECT_REPONAME: nvim-go
    steps:
      - type: checkout
      - type: shell
        name: "Install nvim and gb binary"
        command: |
          set -eux
          wget -q -O - https://github.com/neovim/neovim/releases/download/nightly/neovim-linux64.tar.gz | tar xzf - --strip-components=1 -C "/usr/local"
          nvim --version
          go get github.com/constabulary/gb/...
      - type: shell
        environment:
          COVERAGE_SERVICE: "codecov"
        command: |
          ./scripts/coverage.sh
      - type: shell
        name: "Uploading reports to codecov"
        command: |
          bash <(curl -s https://codecov.io/bash)
