---
version: 2
executorType: docker
containerInfo:
  - image: golang:1.8  # Use latest stable version

stages:
  build:
    workDir: '/go/src/github.com/zchee/nvim-go'

    environment:  # global environment variables
      CIRCLE_PROJECT_USERNAME: zchee    # need codecov coverage script
      CIRCLE_PROJECT_REPONAME: nvim-go  # need codecov coverage script

    steps:
      - type: checkout

      - type: shell
        name: "Install nvim binary"
        command: |
          set -eux
          wget -q -O - https://github.com/neovim/neovim/releases/download/nightly/neovim-linux64.tar.gz | tar xzf - --strip-components=1 -C "/usr/local"
          nvim --version

      - type: shell
        name: "Install go dependencies tools"
        command: |
          go get -u github.com/constabulary/gb/...

      - type: shell
        environment:
          COVERAGE_SERVICE: 'codecov'
        command: |
          ./scripts/coverage.sh

      - type: shell
        name: "Uploading coverage reports to codecov"
        command: |
          bash <(curl -s https://codecov.io/bash)
