required = [
  "golang.org/x/tools/cmd/guru",
]

[metadata]
  project = "nvim-go"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "v2"
  name = "github.com/go-yaml/yaml"

[[constraint]]
  branch = "master"
  name = "github.com/golang/lint"

[[constraint]]
  branch = "master"
  name = "github.com/motemen/go-astmanip"

[[constraint]]
  branch = "master"
  name = "github.com/neovim/go-client"

[[constraint]]
  branch = "master"
  name = "github.com/zchee/go-xdgbasedir"

[[constraint]]
  branch = "master"
  name = "go.uber.org/zap"

[[constraint]]
  name = "github.com/derekparker/delve"
  revision = "92dad944d7e0c1e0affb64d7a45e9ce8c5704fe5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[override]]
  name = "golang.org/x/arch"
  revision = "58ea1a195b1a354bcd572b7ef6bbbd264dc63732"

[[constraint]]
  branch = "master"
  name = "github.com/hokaccha/go-prettyjson"
