version: 2

defaults: &defaults
  working_directory: /go/src/github.com/zchee/nvim-go

jobs:
  build-linux:
    docker:
      - image: golang:1.11.0-stretch
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install nvim binary
          command: |
            set -eux
            wget -q -O - https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz | tar xzf - --strip-components=1 -C "/usr/local"
            nvim --version
      - run:
          name: Install go dependencies tools
          command: |
            go get -u \
              github.com/constabulary/gb/cmd/... \
              github.com/jstemmer/go-junit-report
      - run:
          name: "Take a coverage"
          command: |
            mkdir -p test-results/linux
            go test -v -race -covermode=atomic -coverprofile=coverage.out -coverpkg=./pkg/... $(go list ./pkg/...) 2>&1 | go-junit-report > test-results/linux/results.xml
      - run:
          name: "Send coverage reports to codecov.io"
          command: |
            bash <(curl -s https://codecov.io/bash) -Z
      - store_test_results:
          path: test-results

  build-macos:
    macos:
      xcode: "10.0.0"
    environment:
      PATH: "/Users/distiller/go/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
      GOPATH: "/Users/distiller/go"
      HOMEBREW_NO_AUTO_UPDATE: "1"
    working_directory: ~/go/src/github.com/zchee/nvim-go
    shell: /bin/bash --login -eux -o pipefail
    steps:
      - checkout
      - run:
          name: Install nvim binary
          command: |
            set -eux
            curl -SO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz | tar xzf - --strip-components=1 -C "/usr/local"
            nvim --version
      - run:
          name: install latest go
          command: |
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/go.rb || true
      - run:
          name: show versions
          command: |
            uname -a
            sw_vers
            xcodebuild -version
            system_profiler SPHardwareDataType
            go version
      - run:
          name: "Install go dependencies tools"
          command: |
            go get -u \
              github.com/constabulary/gb/cmd/... \
              github.com/jstemmer/go-junit-report
      - run:
          name: "Take a coverage"
          command: |
            mkdir -p test-results/darwin
            go test -v -race -covermode=atomic -coverprofile=coverage.out -coverpkg=./pkg/... $(go list ./pkg/...) 2>&1 | go-junit-report > test-results/darwin/results.xml
      - run:
          name: "Send coverage reports to codecov.io"
          command: |
            bash <(curl -s https://codecov.io/bash) -Z
      - store_test_results:
          path: test-results

  reviewdog:
    docker:
      - image: golang:1.11.0-stretch
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run reviewdog
          command: |
            go get -u github.com/haya14busa/reviewdog/cmd/reviewdog
            reviewdog -reporter="github-pr-review"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-linux:
          context: org-global
      - build-macos:
          context: org-global
      - reviewdog:
          context: org-global
          filters:
            branches:
              ignore: master
